pgdrv: read-only member ‘vm_flags' (v6.3 compat)
The series ending in Linux commit [1] has made it mandatory to access
vma->vm_flags using the wrappers introduced in same series.

Update the code accordingly.

This fixes the following compilation error:
  CC [M]  pgdrv.o
pgdrv.c: In function ‘dev_mmap’:
pgdrv.c:339:23: error: assignment of read-only member ‘vm_flags’
  339 |         vma->vm_flags |= VM_IO;
      |                       ^~

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=601c3c29dbeb [1]
      ("mm: introduce vm_flags_reset_once to replace WRITE_ONCE vm_flags updates")
Signed-off-by: André Draszik <git@andred.net>